// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqLoruJQJvncg7Ha5mSVermfhDbkIfqng',
    appId: '1:303225427238:web:e8d5e2cfd47351e9399de7',
    messagingSenderId: '303225427238',
    projectId: 'flutter-5226c',
    authDomain: 'flutter-5226c.firebaseapp.com',
    storageBucket: 'flutter-5226c.appspot.com',
    measurementId: 'G-YY4SGZYK1P',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCFA9WaiY1z3KIEzwJD7Vs-c_ANr_8Wvc',
    appId: '1:303225427238:ios:b67b5331f0ac5035399de7',
    messagingSenderId: '303225427238',
    projectId: 'flutter-5226c',
    storageBucket: 'flutter-5226c.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCFA9WaiY1z3KIEzwJD7Vs-c_ANr_8Wvc',
    appId: '1:303225427238:ios:b67b5331f0ac5035399de7',
    messagingSenderId: '303225427238',
    projectId: 'flutter-5226c',
    storageBucket: 'flutter-5226c.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

}